# Copyright Myles Trevino
# Licensed under the Apache License, Version 2.0
# http://www.apache.org/licenses/LICENSE-2.0


version: 2.1


executors:
  chatsifter-executor:
      docker:
        - image: cimg/node:lts-browsers
      working_directory: ~/chatsifter


jobs:
  install:
    executor: chatsifter-executor
    steps:
      - checkout
      - restore_cache:
          key: chatsifter-{{.Branch}}-{{checksum "package-lock.json"}}
      - run: npm i --no-save
      - save_cache:
          key: chatsifter-{{.Branch}}-{{checksum "package-lock.json"}}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    executor: chatsifter-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  lint:
    executor: chatsifter-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run lint

workflows:
  version: 2
  workflow:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - build
